/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ventana.java
 *
 * Created on 15-04-2013, 11:50:03 PM
 */
package splash;
import com.sun.awt.AWTUtilities;
import opticx1.Cargar_splash;
import com.sun.awt.AWTUtilities;
import java.awt.Color;
import opticx1.VentanaUsuario;
import opticx1.Ventanaadmin;
import opticx1.login;


/**
 *
 * @author IsraelCM
 */
public final class ventana1 extends javax.swing.JFrame {

    /** Creates new form ventana */
    
    double i=50, j=1;
    Cargar_splash hilo;
    public ventana1() {
        initComponents();
        iniciar();
    }
    public void iniciar(){
        
        setLocationRelativeTo(null);
        Progreso.setVisible(true);
        Progreso.setBackground(Color.BLUE);
        hilo=new Cargar_splash(getProgreso());
        hilo.start();
        hilo=null;
        lblInvitado.setVisible(true);
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Progreso = new javax.swing.JProgressBar();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        estados = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(460, 325));
        setMinimumSize(new java.awt.Dimension(460, 325));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(460, 325));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Progreso.setBackground(new java.awt.Color(0, 153, 0));
        Progreso.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                ProgresoStateChanged(evt);
            }
        });
        getContentPane().add(Progreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 600, 10));

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setForeground(new java.awt.Color(0, 10, 50));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblInvitado.setBackground(new java.awt.Color(255, 255, 255));
        lblInvitado.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblInvitado.setForeground(new java.awt.Color(0, 0, 102));
        lblInvitado.setText("Categoria");
        jPanel1.add(lblInvitado, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, -1, -1));

        nomuser.setBackground(new java.awt.Color(255, 255, 255));
        nomuser.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        nomuser.setForeground(new java.awt.Color(0, 51, 102));
        nomuser.setText("Usuario");
        jPanel1.add(nomuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Bienvenido:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 430, 40));

        estados.setText("Cargando modulos...");
        getContentPane().add(estados, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 450, -1));

        jLabel1.setBackground(new java.awt.Color(0, 102, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/splash/img/opticx logo5.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 450, 270));

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void ProgresoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_ProgresoStateChanged
    if(Progreso.getValue()==i){
        if(j!=101){
            AWTUtilities.setWindowOpacity(this, Float.valueOf((100-j)/100+"f"));
            i++;
            j+=2;
        }
    }
     if (Progreso.getValue() == 10) {
               estados.setText("Comprobando conexión a base de datos "); 
            }
    if (Progreso.getValue() == 20) {
               estados.setText("Cargando iconos"); 
            }
            if (Progreso.getValue() == 30) {
                estados.setText("Preparando interfaz de usuario");
            }
            if (Progreso.getValue() == 40) {
                estados.setText("Creando el entorno de la aplicación");
            }
            if (Progreso.getValue() == 50) {
                estados.setText("Terminando...");
            }
            if (Progreso.getValue() == 60) {
                estados.setText("Listo");
            }
    if(Progreso.getValue()==100){
         Ventanaadmin adm=new Ventanaadmin();
        adm.setVisible(true);
        adm.pack();
        Ventanaadmin.lblconectadoadmin.setText(login.Guardausuario);
        this.dispose();
        
    }
}//GEN-LAST:event_ProgresoStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new ventana1().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar Progreso;
    private javax.swing.JLabel estados;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    public static final javax.swing.JLabel lblInvitado = new javax.swing.JLabel();
    public static final javax.swing.JLabel nomuser = new javax.swing.JLabel();
    // End of variables declaration//GEN-END:variables

    /**
     * @return the Progreso
     */
    public javax.swing.JProgressBar getProgreso() {
        return Progreso;
    }

    /**
     * @param Progreso the Progreso to set
     */
    public void setProgreso(javax.swing.JProgressBar Progreso) {
        this.Progreso = Progreso;
    }
}
