/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Micas;

import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import opticx1.control_existencias;

/**
 *
 * @author LEO
 */
public class AltaMicas extends javax.swing.JInternalFrame {
    control_existencias con = new control_existencias();

    /**
     * Creates new form AltaMicas
     */
    public AltaMicas() {
        initComponents();      
        CargarControles();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gbTipoEnfermedad = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        pnlBifocal = new javax.swing.JPanel();
        cbxTipoBifocal = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        cbxTipoLente = new javax.swing.JComboBox<>();
        pnlTiposGenerales = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cboTipoMaterial = new javax.swing.JComboBox<>();
        cboTipoTratamiento = new javax.swing.JComboBox<>();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        chkCombinado = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        cboMiopia = new javax.swing.JComboBox<>();
        cboHipermetropia = new javax.swing.JComboBox<>();
        cboAstigmatismo = new javax.swing.JComboBox<>();
        rbMiopia = new javax.swing.JRadioButton();
        rbHipermetropia = new javax.swing.JRadioButton();
        rbAstigmatismo = new javax.swing.JRadioButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtClave = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        pnlInfoAdicional = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Alta de Micas");
        setAutoscrolls(true);
        try {
            setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        setVisible(true);

        jScrollPane1.setAutoscrolls(true);

        jPanel1.setAutoscrolls(true);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setAutoscrolls(true);

        jButton1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Micas/images/clean.png"))); // NOI18N
        jButton1.setText("NUEVO");
        jButton1.setAutoscrolls(true);
        jButton1.setIconTextGap(10);

        jButton3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Micas/images/edit.png"))); // NOI18N
        jButton3.setText("EDITAR");
        jButton3.setIconTextGap(10);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        btnGuardar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Micas/images/save.png"))); // NOI18N
        btnGuardar.setText("GUARDAR");
        btnGuardar.setIconTextGap(10);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addGap(18, 18, 18)
                .addComponent(btnGuardar)
                .addContainerGap(857, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(jButton3)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 1260, 50));

        pnlBifocal.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlBifocal.setAutoscrolls(true);

        cbxTipoBifocal.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        cbxTipoBifocal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxTipoBifocal.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxTipoBifocalItemStateChanged(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel6.setText("TIPO DE BIFOCAL");

        javax.swing.GroupLayout pnlBifocalLayout = new javax.swing.GroupLayout(pnlBifocal);
        pnlBifocal.setLayout(pnlBifocalLayout);
        pnlBifocalLayout.setHorizontalGroup(
            pnlBifocalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBifocalLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(pnlBifocalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBifocalLayout.createSequentialGroup()
                        .addComponent(cbxTipoBifocal, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBifocalLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(46, 46, 46))))
        );
        pnlBifocalLayout.setVerticalGroup(
            pnlBifocalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBifocalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(cbxTipoBifocal, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jPanel1.add(pnlBifocal, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 200, 110));

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.setAutoscrolls(true);

        jLabel7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel7.setText("TIPO DE LENTE");

        cbxTipoLente.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        cbxTipoLente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxTipoLente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbxTipoLenteMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cbxTipoLenteMousePressed(evt);
            }
        });
        cbxTipoLente.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxTipoLenteItemStateChanged(evt);
            }
        });
        cbxTipoLente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxTipoLenteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(55, 55, 55))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(cbxTipoLente, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(cbxTipoLente, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 200, 110));

        pnlTiposGenerales.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlTiposGenerales.setAutoscrolls(true);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setText("TIPO DE TRATAMIENTO");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setText("TIPO DE MATERIAL");

        cboTipoMaterial.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        cboTipoMaterial.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cboTipoTratamiento.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        cboTipoTratamiento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setText("TIPO DE ENFERMEDAD");

        chkCombinado.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        chkCombinado.setText("  Combinado");
        chkCombinado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkCombinadoActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel8.setText("GRADUACIÓN");

        cboMiopia.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        cboMiopia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Selecciona --", "- 0.25", "- 0.5", "- 0.75", "- 1.0", "- 1.25", "- 1.5", "- 1.75", "- 2.0", "- 2.25", "- 2.5", "- 2.75", "- 3.0", "- 3.25", "- 3.5", "- 3.75", "- 4.0", "- 4.25", "- 4.5", "- 4.75", "- 5.0", "- 5.25", "- 5.5", "- 5.75", "- 6.0", "- 6.25", "- 6.5", "- 6.75", "- 7.0", "- 7.25", "- 7.5", "- 7.75", "- 8.0" }));

        cboHipermetropia.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        cboHipermetropia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Selecciona -- ", "+ 0.25", "+ 0.5", "+ 0.75", "+ 1.0", "+ 1.25", "+ 1.5", "+ 1.75", "+ 2.0", "+ 2.25", "+ 2.5", "+ 2.75", "+ 3.0", "+ 3.25", "+ 3.5", "+ 3.75", "+ 4.0", "+ 4.25", "+ 4.5", "+ 4.75", "+ 5.0", "+ 5.25", "+ 5.5", "+ 5.75", "+ 6.0", "+ 6.25", "+ 6.5", "+ 6.75", "+ 7.0", "+ 7.25", "+ 7.5", "+ 7.75", "+ 8.0" }));

        cboAstigmatismo.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        cboAstigmatismo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Selecciona --", "0°", "5°", "10°", "15°", "20°", "25°", "30°", "35°", "40°", "45°", "50°", "55°", "60°", "65°", "70°", "75°", "80°", "85°", "90°", "95°", "100°", "105°", "110°", "115°", "120°", "125°", "130°", "135°", "140°", "145°", "150°", "155°", "160°", "165°", "170°", "175°", "180°" }));
        cboAstigmatismo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboAstigmatismoActionPerformed(evt);
            }
        });

        rbMiopia.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        rbMiopia.setText("Miopía (Esfera ( - ))");
        rbMiopia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbMiopiaActionPerformed(evt);
            }
        });

        rbHipermetropia.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        rbHipermetropia.setText("Hipermetropía (Esfera ( + ))");
        rbHipermetropia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbHipermetropiaActionPerformed(evt);
            }
        });

        rbAstigmatismo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        rbAstigmatismo.setText("Astigmatismo (Cilindro)");
        rbAstigmatismo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbAstigmatismoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(chkCombinado)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(rbMiopia)
                            .addComponent(rbHipermetropia)
                            .addComponent(rbAstigmatismo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cboHipermetropia, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(cboMiopia, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboAstigmatismo, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(59, Short.MAX_VALUE))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboMiopia, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbMiopia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboAstigmatismo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbAstigmatismo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboHipermetropia, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbHipermetropia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chkCombinado)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel13.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel13.setText("CLAVE");

        jLabel14.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel14.setText("DESCRIPCIÓN");

        txtClave.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtClave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClaveActionPerformed(evt);
            }
        });

        jTextField5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField5)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtClave, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtClave, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlTiposGeneralesLayout = new javax.swing.GroupLayout(pnlTiposGenerales);
        pnlTiposGenerales.setLayout(pnlTiposGeneralesLayout);
        pnlTiposGeneralesLayout.setHorizontalGroup(
            pnlTiposGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTiposGeneralesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTiposGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlTiposGeneralesLayout.createSequentialGroup()
                        .addGroup(pnlTiposGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cboTipoTratamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(68, 68, 68))
                    .addGroup(pnlTiposGeneralesLayout.createSequentialGroup()
                        .addGroup(pnlTiposGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cboTipoMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(125, 125, 125))))
        );
        pnlTiposGeneralesLayout.setVerticalGroup(
            pnlTiposGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTiposGeneralesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(pnlTiposGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlTiposGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboTipoTratamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboTipoMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(pnlTiposGenerales, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, 560, 430));

        pnlInfoAdicional.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel9.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel9.setText("PRECIO DE COMPRA");

        jLabel10.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel10.setText("PRECIO DE VENTA");

        jLabel11.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel11.setText("STOCK");

        jLabel12.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel12.setText("OBSERVACIONES");

        jTextField3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jTextField4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane3.setViewportView(jTextArea1);

        jTextField2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlInfoAdicionalLayout = new javax.swing.GroupLayout(pnlInfoAdicional);
        pnlInfoAdicional.setLayout(pnlInfoAdicionalLayout);
        pnlInfoAdicionalLayout.setHorizontalGroup(
            pnlInfoAdicionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInfoAdicionalLayout.createSequentialGroup()
                .addGroup(pnlInfoAdicionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlInfoAdicionalLayout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(pnlInfoAdicionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9)
                            .addGroup(pnlInfoAdicionalLayout.createSequentialGroup()
                                .addGap(104, 104, 104)
                                .addComponent(jLabel11))
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlInfoAdicionalLayout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlInfoAdicionalLayout.createSequentialGroup()
                .addGap(0, 54, Short.MAX_VALUE)
                .addGroup(pnlInfoAdicionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );
        pnlInfoAdicionalLayout.setVerticalGroup(
            pnlInfoAdicionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInfoAdicionalLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        jPanel1.add(pnlInfoAdicional, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 70, 380, 430));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Micas/images/fondo2.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.setMaximumSize(new java.awt.Dimension(1366, 768));
        jLabel2.setMinimumSize(new java.awt.Dimension(1366, 768));
        jLabel2.setPreferredSize(new java.awt.Dimension(1366, 768));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1125, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void cbxTipoBifocalItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxTipoBifocalItemStateChanged
        if (cbxTipoBifocal.getSelectedItem()!= "SELECCIONA:"){
            pnlTiposGenerales.setVisible(true);
            pnlInfoAdicional.setVisible(true);
            btnGuardar.setEnabled(true);
            txtClave.requestFocus();
            CargarCombosTipos();
        }else{
            pnlTiposGenerales.setVisible(false);
            pnlInfoAdicional.setVisible(false);
            btnGuardar.setEnabled(false);
        }
    }//GEN-LAST:event_cbxTipoBifocalItemStateChanged

    private void cbxTipoLenteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbxTipoLenteMouseClicked

    }//GEN-LAST:event_cbxTipoLenteMouseClicked

    private void cbxTipoLenteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbxTipoLenteMousePressed

    }//GEN-LAST:event_cbxTipoLenteMousePressed

    private void cbxTipoLenteItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxTipoLenteItemStateChanged
        if (cbxTipoLente.getSelectedItem().equals("Monofocal")){
            pnlBifocal.setVisible(false);
            cbxTipoBifocal.removeAllItems();
            pnlTiposGenerales.setVisible(true);
            pnlInfoAdicional.setVisible(true);
            btnGuardar.setEnabled(true);
            txtClave.requestFocus();
            CargarCombosTipos();
        }else if (cbxTipoLente.getSelectedItem().equals("Bifocal")){

            try {
                Object[] llenar_combo = con.combox("tipo_de_bifocal", "TIPO_BIFO_NOMB");
                cbxTipoBifocal.removeAllItems();
                cbxTipoBifocal.addItem("SELECCIONA:");
                for (int i = 0; i < llenar_combo.length; i++) {

                    cbxTipoBifocal.addItem((String) llenar_combo[i]);
                }

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "¡Error! no se ha podido acceder ala base de datos para cargar la lista de Tipo de Bifocal");
            }
            pnlBifocal.setVisible(true);
            pnlTiposGenerales.setVisible(false);
            pnlInfoAdicional.setVisible(false);
            btnGuardar.setEnabled(false);
        }
        else if (cbxTipoLente.getSelectedItem().equals("SELECCIONA:")){
            pnlBifocal.setVisible(false);
            pnlTiposGenerales.setVisible(false);
            pnlInfoAdicional.setVisible(false);
            btnGuardar.setEnabled(false);
            cbxTipoBifocal.removeAllItems();
        }
    }//GEN-LAST:event_cbxTipoLenteItemStateChanged

    private void cbxTipoLenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxTipoLenteActionPerformed

    }//GEN-LAST:event_cbxTipoLenteActionPerformed

    private void chkCombinadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkCombinadoActionPerformed
        try {
            if (chkCombinado.isSelected()){
                gbTipoEnfermedad.remove(rbMiopia);
                gbTipoEnfermedad.remove(rbAstigmatismo);
                gbTipoEnfermedad.remove(rbHipermetropia);
            } else{
                gbTipoEnfermedad.add(rbMiopia);
                gbTipoEnfermedad.add(rbAstigmatismo);
                gbTipoEnfermedad.add(rbHipermetropia);
                gbTipoEnfermedad.clearSelection();
                cboMiopia.setEnabled(false);
                cboMiopia.setSelectedIndex(0);
                cboAstigmatismo.setEnabled(false);
                cboAstigmatismo.setSelectedIndex(0);
                cboHipermetropia.setEnabled(false);
                cboHipermetropia.setSelectedIndex(0);
            }

        } catch (Exception e) {
        }
    }//GEN-LAST:event_chkCombinadoActionPerformed

    private void cboAstigmatismoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboAstigmatismoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboAstigmatismoActionPerformed

    private void rbMiopiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbMiopiaActionPerformed
        try {
            if (rbMiopia.isSelected()){
                cboMiopia.setEnabled(true);
                if (chkCombinado.isSelected()==false){
                    cboHipermetropia.setEnabled(false);
                    cboHipermetropia.setSelectedIndex(0);
                    cboAstigmatismo.setEnabled(false);
                    cboAstigmatismo.setSelectedIndex(0);
                }
            }else
            cboMiopia.setEnabled(false);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_rbMiopiaActionPerformed

    private void rbHipermetropiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbHipermetropiaActionPerformed
        try {
            if (rbHipermetropia.isSelected()){
                cboHipermetropia.setEnabled(true);
                if (chkCombinado.isSelected()==false){
                    cboMiopia.setEnabled(false);
                    cboMiopia.setSelectedIndex(0);
                    cboAstigmatismo.setEnabled(false);
                    cboAstigmatismo.setSelectedIndex(0);
                }

            }else
            cboHipermetropia.setEnabled(false);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_rbHipermetropiaActionPerformed

    private void rbAstigmatismoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbAstigmatismoActionPerformed
        try {
            if (rbAstigmatismo.isSelected()){
                cboAstigmatismo.setEnabled(true);
                if (chkCombinado.isSelected()==false){
                    cboMiopia.setEnabled(false);
                    cboMiopia.setSelectedIndex(0);
                    cboHipermetropia.setEnabled(false);
                    cboHipermetropia.setSelectedIndex(0);
                }
            }else
            cboAstigmatismo.setEnabled(false);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_rbAstigmatismoActionPerformed

    private void txtClaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClaveActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<String> cboAstigmatismo;
    private javax.swing.JComboBox<String> cboHipermetropia;
    private javax.swing.JComboBox<String> cboMiopia;
    private javax.swing.JComboBox<String> cboTipoMaterial;
    private javax.swing.JComboBox<String> cboTipoTratamiento;
    private javax.swing.JComboBox<String> cbxTipoBifocal;
    private javax.swing.JComboBox<String> cbxTipoLente;
    private javax.swing.JCheckBox chkCombinado;
    private javax.swing.ButtonGroup gbTipoEnfermedad;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JPanel pnlBifocal;
    private javax.swing.JPanel pnlInfoAdicional;
    private javax.swing.JPanel pnlTiposGenerales;
    private javax.swing.JRadioButton rbAstigmatismo;
    private javax.swing.JRadioButton rbHipermetropia;
    private javax.swing.JRadioButton rbMiopia;
    private javax.swing.JTextField txtClave;
    // End of variables declaration//GEN-END:variables
public void CargarControles()
{
    try{
    
try {
            Object[] llenar_combo = con.combox("tipo_de_lente", "TIPO_LENT_NOMB");
            cbxTipoLente.removeAllItems();
            cbxTipoLente.addItem("SELECCIONA:");
            for (int i = 0; i < llenar_combo.length; i++) {

                cbxTipoLente.addItem((String) llenar_combo[i]);
            }

        } catch (Exception e) {
            Object[] llenar_combo = con.combox("tipo_de_lente", "TIPO_LENT_NOMB");
            cbxTipoLente.removeAllItems();
            cbxTipoLente.addItem("SELECCIONA:");
            for (int i = 0; i < llenar_combo.length; i++) {

                cbxTipoLente.addItem((String) llenar_combo[i]);
            }
        }
} catch (Exception e) {
    JOptionPane.showMessageDialog(null, "¡Error! no se ha podido acceder ala base de datos para cargar la lista de Tipo de lente");
            System.out.println(e);
}
     pnlBifocal.setVisible(false);
     pnlTiposGenerales.setVisible(false);
     pnlInfoAdicional.setVisible(false);
     btnGuardar.setEnabled(false);
     cboMiopia.setEnabled(false);
     cboAstigmatismo.setEnabled(false);
     cboHipermetropia.setEnabled(false);
}
private void CargarCombosTipos()
{

    
try {
            Object[] llenar_combo = con.combox("tipo_de_material", "TIPO_MATE_NOMB");
            cboTipoMaterial.removeAllItems();
            cboTipoMaterial.addItem("SELECCIONA:");
            for (int i = 0; i < llenar_combo.length; i++) {

                cboTipoMaterial.addItem((String) llenar_combo[i]);
            }
             Object[] llenar_combo_tratamiento = con.combox("tipo_de_tratamiento", "TIPO_TRAT_NOMB");
            cboTipoTratamiento.removeAllItems();
            cboTipoTratamiento.addItem("SELECCIONA:");
            for (int i = 0; i < llenar_combo_tratamiento.length; i++) {

                cboTipoTratamiento.addItem((String) llenar_combo_tratamiento[i]);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "¡Error! no se ha podido acceder ala base de datos para cargar la lista de Tipo de Material y Tipo de tratamiento");
            System.out.println(e);
            }
        }
}

