/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package opticx1;

/**
 *
 * @author LEO
 */
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;
import splash.VentanaUnoAntes;
import splash.ventana1;
import splash.ventana2;
public class login extends javax.swing.JFrame {
        Conexionbd cc= new Conexionbd();
         Connection cn = cc.conexion();
         public static String Guardausuario;
         public static String invitado;
    /**
     * Creates new form login
     */
    public login(){
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("SiGOO");
        botonenter();
       
    }
       void acceder(String usuario, String pass)
    {
        String cap="";
        String esta="";
            
        String sql="SELECT USUA_NOMB, USUA_PASS, NUSU_NOMB, ESTA_USUA_NOMB"
                + " FROM usuarios INNER JOIN nivelusuarios INNER JOIN estatus_usuarios"
                + " ON USUA_NUSU_ID=NUSU_ID AND USUA_ESTA_USUA_ID=ESTA_USUA_ID WHERE USUA_NOMB='"+usuario+"' && USUA_PASS='"+pass+"'";
        
        try {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while(rs.next())
            {
                cap=rs.getString("NUSU_NOMB");
                System.out.println(cap+ " categoria usuario");
                esta=rs.getString("ESTA_USUA_NOMB");
            }
            if(cap.equals("ADMINISTRADOR") && esta.equals("ACTIVO"))
            {
                invitado=cap;  
                this.setVisible(false);
                  //   VentanaUnoAntes ingreso = new VentanaUnoAntes();
                 ventana1 ingreso = new ventana1();
                    ingreso.setVisible(true);
                    ingreso.pack();
                   // VentanaUnoAntes.nomuser.setText(usuario);
                    ventana1.lblInvitado.setText(invitado);
                    ventana1.nomuser.setText(usuario);
                    Guardausuario=usuario.toString();
                   
        
                
            }
            else if(cap.equals("INVITADO")&& esta.equals("ACTIVO"))
            {
                invitado=cap;
            this.setVisible(false);
                   ventana2 ingreso = new ventana2();
                    ingreso.setVisible(true);
                    ingreso.pack();
                   ventana2.lblInvitado.setText(invitado);
                    ventana2.nomuser.setText(usuario);
                    Guardausuario=usuario.toString();
                     
                     System.out.println(invitado);
            }
            
            else if((!cap.equals("Administrador"))&& (!cap.equals("Invitado")))
            {
                JOptionPane.showMessageDialog(this, "Usuario o contraseña incorrectos");
                usuariotxt.setText("");
                contraseñatxt.setText("");
                usuariotxt.requestFocus();
            }
        } catch (SQLException ex) {
            Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
        }
       
        }  
       
       
    public static void botonenter() {
 
        
 
        // set this panel's layout to null for absolute positioning of components
        
 
        
 
        jButton2.registerKeyboardAction(jButton2.getActionForKeyStroke(
                                      KeyStroke.getKeyStroke(KeyEvent.VK_SPACE, 0, false)),
                                      KeyStroke.getKeyStroke(KeyEvent.VK_ENTER, 0, false),
                                      JComponent.WHEN_FOCUSED);
 
        jButton2.registerKeyboardAction(jButton2.getActionForKeyStroke(
                                      KeyStroke.getKeyStroke(KeyEvent.VK_SPACE, 0, true)),
                                      KeyStroke.getKeyStroke(KeyEvent.VK_ENTER, 0, true),
                                      JComponent.WHEN_FOCUSED);
 
    
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        usuariotxt = new javax.swing.JTextField();
        contraseñatxt = new javax.swing.JPasswordField();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS BOTONES/LOGIN/LOGIN3.png"))); // NOI18N
        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(350, 420));
        setPreferredSize(new java.awt.Dimension(350, 420));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("USUARIO");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 70, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("CONTRASEÑA");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        usuariotxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        usuariotxt.setToolTipText("Ingresa tu nombre de usuario.");
        usuariotxt.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        usuariotxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuariotxtActionPerformed(evt);
            }
        });
        getContentPane().add(usuariotxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 170, 30));

        contraseñatxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        contraseñatxt.setToolTipText("Ingresa tu contraseña.");
        contraseñatxt.setAutoscrolls(false);
        contraseñatxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contraseñatxtActionPerformed(evt);
            }
        });
        contraseñatxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                contraseñatxtKeyTyped(evt);
            }
        });
        getContentPane().add(contraseñatxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 170, 30));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS BOTONES/GO PARA ENTRAR/WEY2.png"))); // NOI18N
        jButton2.setMnemonic('E');
        jButton2.setText("ENTRAR");
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setIconTextGap(1);
        jButton2.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS BOTONES/GO PARA ENTRAR/WEY3.png"))); // NOI18N
        jButton2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS BOTONES/GO PARA ENTRAR/WEY1.png"))); // NOI18N
        jButton2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 300, -1, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS BOTONES/SALIR IMG/SALIR3.png"))); // NOI18N
        jButton1.setMnemonic('S');
        jButton1.setText("SALIR");
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setIconTextGap(1);
        jButton1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS BOTONES/SALIR IMG/SALIR4.png"))); // NOI18N
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS BOTONES/SALIR IMG/SALIR2.png"))); // NOI18N
        jButton1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setText("INGRESAR AL SISTEMA");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 200, 20));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS BOTONES/LOGIN/LOGIN3.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, 90));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // boton salir del programa
        botonenter();

        int dato=JOptionPane.showConfirmDialog(null, "¿Estas seguro de salir?", "Alerta!", JOptionPane.YES_NO_OPTION);
        if (dato==0){
            //se puede regresar aqui el codigo salir para quitar el ultimo
            System.exit(0);

        }       else{
            usuariotxt.setText("");
            contraseñatxt.setText("");

        }
        usuariotxt.requestFocus();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // boton de entrar para usuario y contraseña
          String usu=usuariotxt.getText();
    String pas=new String(contraseñatxt.getPassword());
    acceder(usu, pas);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void contraseñatxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contraseñatxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contraseñatxtActionPerformed

    private void usuariotxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuariotxtActionPerformed
        // TODO add your handling code here:
        usuariotxt.requestFocus();
    }//GEN-LAST:event_usuariotxtActionPerformed

    private void contraseñatxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contraseñatxtKeyTyped
        // TODO add your handling code here:
        char teclapresionada=evt.getKeyChar();

         if(teclapresionada==KeyEvent.VK_ENTER){

        jButton2.doClick();
       
    //o bien puedes colocar algún método que tengas.
         }
    }//GEN-LAST:event_contraseñatxtKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new login().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    
    public void keyPressed(KeyEvent ke){

if (ke.getKeyCode() == KeyEvent.VK_ENTER) 
{
Object src = ke.getSource();
Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(
new ActionEvent(src, 
ActionEvent.ACTION_PERFORMED, 
"Enter"));
}
// end keyPressed()

    }
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField contraseñatxt;
    private javax.swing.JButton jButton1;
    public static javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField usuariotxt;
    // End of variables declaration//GEN-END:variables
}




