/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package opticx1;

import Clientes.Clientes;
import Micas.Micas;
import Pacientes.Historia_clinica;
import Usuarios.MenuUsuarios;
import Ventas.MenuVentas;

import empleados.ctrlempleado;
import inventario.ctrlinventario;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractAction;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;
import static opticx1.login.Guardausuario;
import static opticx1.login.invitado;
/**
 *
 * @author LEO
 */
public class VentanaUsuario extends javax.swing.JFrame {
private static VentanaUsuario _ventana;  // para tecla escape
public static VentanaUsuario getInstance(){ return _ventana;}   // para tecla escape
public static String Invitado;
public static boolean invi=false;
    /**
     * Creates new form Ventanaadmin
     */
    public VentanaUsuario() {
        initComponents();
        setTitle("Sistema de Gestión para Opticx Ópticas");
        lblconectadoUser.setText(login.Guardausuario);
        try {
            btnClie.setVisible(false);
        btnUser.setVisible(false);
        btnEmpl.setVisible(false);
        } catch (Exception e) {
            btnClie.setVisible(false);
        btnUser.setVisible(false);
        btnEmpl.setVisible(false);
        }
        
        if (invitado.equals("INVITADO")){
        invi=true;
    }
        else{
            invi=false;
        }
        
        jButton16.setMnemonic(KeyEvent.VK_F12);
       
        
        
        
        getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).
        put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), "CERRAR");
getRootPane().getActionMap().put("CERRAR", new AbstractAction()
{
    @Override
    public void actionPerformed(ActionEvent ae)
    {
        _ventana.dispose();
    }
});


       


    }
   
    
    
    private void teclaPresionada(int tecla) {
        if (tecla == KeyEvent.VK_F1){
            System.exit(0);
        }
    }  
         private void teclaPresionadacerrarsesion(int tecla) {
        if (tecla == KeyEvent.VK_F12){
            login l = null;
        try {
            l = new login();
        } catch (Exception ex) {
            Logger.getLogger(VentanaUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
        l.setVisible(true);
        this.dispose();
        }
        
        //teclaPresionadacerrarsesion(evt.getKeyCode()); Se coloca dentro del jButton Pressed
        //para que al hacer clic se active
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ElegirInventario = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        lblconectadoUser = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        btnClie = new javax.swing.JButton();
        btnEmpl = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        btnUser = new javax.swing.JButton();
        clockFace1 = new org.edisoncor.gui.varios.ClockFace();
        jCalendar1 = new com.toedter.calendar.JCalendar();
        jLabel2 = new javax.swing.JLabel();

        ElegirInventario.setMinimumSize(new java.awt.Dimension(360, 250));
        ElegirInventario.setResizable(false);
        ElegirInventario.setType(java.awt.Window.Type.UTILITY);
        ElegirInventario.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton23.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventario/Imagenes/ant2.png"))); // NOI18N
        jButton23.setText("PRODUCTOS");
        jButton23.setBorderPainted(false);
        jButton23.setContentAreaFilled(false);
        jButton23.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton23.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton23.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/inventario/Imagenes/ant3.png"))); // NOI18N
        jButton23.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/inventario/Imagenes/ant1.png"))); // NOI18N
        jButton23.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton23.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jButton24.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventario/Imagenes/mic2.png"))); // NOI18N
        jButton24.setText("MICAS");
        jButton24.setBorderPainted(false);
        jButton24.setContentAreaFilled(false);
        jButton24.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton24.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton24.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/inventario/Imagenes/mic3.png"))); // NOI18N
        jButton24.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/inventario/Imagenes/mic1.png"))); // NOI18N
        jButton24.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton24.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton24ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton24, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, -1, -1));

        ElegirInventario.getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 320, 180));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS BOTONES/FONDOS/DIALOGO4.png"))); // NOI18N
        ElegirInventario.getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, -1));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1366, 768));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblconectadoUser.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblconectadoUser.setForeground(new java.awt.Color(153, 0, 0));
        lblconectadoUser.setText("1");
        getContentPane().add(lblconectadoUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 180, 40));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setText("En conexión:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, -1, 40));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/opticx1/img/examenes2.png"))); // NOI18N
        jButton1.setText("Examenes y Pacientes");
        jButton1.setAutoscrolls(true);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setIconTextGap(1);
        jButton1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/opticx1/img/examenes3.png"))); // NOI18N
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/opticx1/img/examenes1.png"))); // NOI18N
        jButton1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 190, 160));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/opticx1/img/venta2.png"))); // NOI18N
        jButton2.setText("Ventas");
        jButton2.setAutoscrolls(true);
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setIconTextGap(1);
        jButton2.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/opticx1/img/venta3.png"))); // NOI18N
        jButton2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/opticx1/img/venta1.png"))); // NOI18N
        jButton2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jButton2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton2KeyPressed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 120, 180, 160));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/opticx1/img/inventario2.png"))); // NOI18N
        jButton3.setMnemonic('i');
        jButton3.setText("Inventario");
        jButton3.setAutoscrolls(true);
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setIconTextGap(1);
        jButton3.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/opticx1/img/inventario3.png"))); // NOI18N
        jButton3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/opticx1/img/inventario1.png"))); // NOI18N
        jButton3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jButton3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jButton3KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jButton3KeyTyped(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 110, 190, 170));

        btnClie.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnClie.setText("Clientes");
        btnClie.setAutoscrolls(true);
        btnClie.setBorderPainted(false);
        btnClie.setContentAreaFilled(false);
        btnClie.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClie.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnClie.setIconTextGap(1);
        btnClie.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnClie.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnClie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClieActionPerformed(evt);
            }
        });
        getContentPane().add(btnClie, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 320, 180, 160));

        btnEmpl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnEmpl.setText("Empleados");
        btnEmpl.setAutoscrolls(true);
        btnEmpl.setBorderPainted(false);
        btnEmpl.setContentAreaFilled(false);
        btnEmpl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEmpl.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEmpl.setIconTextGap(1);
        btnEmpl.setInheritsPopupMenu(true);
        btnEmpl.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnEmpl.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEmpl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmplActionPerformed(evt);
            }
        });
        getContentPane().add(btnEmpl, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, 150, 160));

        jButton16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/opticx1/img/exit.png"))); // NOI18N
        jButton16.setText("Cerrar Sesión");
        jButton16.setAutoscrolls(true);
        jButton16.setBorderPainted(false);
        jButton16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton16.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        jButton16.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jButton16.setIconTextGap(10);
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        jButton16.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton16KeyPressed(evt);
            }
        });
        getContentPane().add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 150, 40));

        btnUser.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnUser.setText("Usuarios");
        btnUser.setAutoscrolls(true);
        btnUser.setBorderPainted(false);
        btnUser.setContentAreaFilled(false);
        btnUser.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnUser.setIconTextGap(1);
        btnUser.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnUser.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserActionPerformed(evt);
            }
        });
        getContentPane().add(btnUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 310, 150, 160));
        getContentPane().add(clockFace1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 110, 160, 160));
        getContentPane().add(jCalendar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 290, 240, 220));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/opticx1/img/fondoadminmenu1.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.setAutoscrolls(true);
        jLabel2.setFocusCycleRoot(true);
        jLabel2.setFocusTraversalPolicyProvider(true);
        jLabel2.setMaximumSize(new java.awt.Dimension(1366, 768));
        jLabel2.setMinimumSize(new java.awt.Dimension(780, 438));
        jLabel2.setName(""); // NOI18N
        jLabel2.setOpaque(true);
        jLabel2.setPreferredSize(new java.awt.Dimension(1366, 768));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 760));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        MenuVentas mv = null;
        try {
            mv = new MenuVentas();
        } catch (Exception ex) {
            Logger.getLogger(VentanaUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
        mv.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Historia_clinica hl = null;
        try {
            hl = new Historia_clinica();
        } catch (Exception ex) {
            Logger.getLogger(VentanaUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
        hl.setVisible(true);
        this.dispose();
                            
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:
        login l = null;
        try {
            l = new login();
        } catch (Exception ex) {
            Logger.getLogger(VentanaUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
        l.setVisible(true);
        this.dispose();
        invitado="";
    }//GEN-LAST:event_jButton16ActionPerformed

    private void btnEmplActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmplActionPerformed
        // TODO add your handling code here:
        ctrlempleado obj=new ctrlempleado();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnEmplActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        ElegirInventario.setModal(true);
        ElegirInventario.setLocationRelativeTo(null);
        ElegirInventario.setVisible(true);
        
       
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton2KeyPressed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_jButton2KeyPressed

    private void jButton16KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton16KeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton16KeyPressed

    private void jButton3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton3KeyReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton3KeyReleased

    private void jButton3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton3KeyTyped
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton3KeyTyped

    private void jButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton24ActionPerformed
       ElegirInventario.dispose();
        Micas mc = null;
        try {
            mc = new Micas();
        } catch (Exception ex) {
            Logger.getLogger(Ventanaadmin.class.getName()).log(Level.SEVERE, null, ex);
        }
        mc.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_jButton24ActionPerformed

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
        ElegirInventario.dispose();
        ctrlinventario l=null;
         String nl = System.getProperty("line.separator");
         try{
               l=new ctrlinventario();
               
               l.setVisible(true);
               this.dispose();
         }catch (Exception e){
            JOptionPane.showMessageDialog(null,"¡Error! "+e);
            
        }
    }//GEN-LAST:event_jButton23ActionPerformed

    private void btnUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserActionPerformed
        MenuUsuarios  m = null;
        try {
            m = new MenuUsuarios();
        } catch (Exception ex) {
            Logger.getLogger(VentanaUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
        m.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnUserActionPerformed

    private void btnClieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClieActionPerformed
        Clientes  c = null;
        try {
            c = new Clientes();
        } catch (Exception ex) {
            Logger.getLogger(VentanaUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
        c.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnClieActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog ElegirInventario;
    private javax.swing.JButton btnClie;
    private javax.swing.JButton btnEmpl;
    private javax.swing.JButton btnUser;
    private org.edisoncor.gui.varios.ClockFace clockFace1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton3;
    private com.toedter.calendar.JCalendar jCalendar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JLabel lblconectadoUser;
    // End of variables declaration//GEN-END:variables
}
